# Lab 1

In [3]:
import numpy as np

## Questions

#### 1. Convert a 1D array into a 2D array with 3 rows.

In [4]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
result = arr.reshape(3, -1)

result

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 2. Replace all odd numbers in the given array with -1.

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1

arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

#### 3. Find the positions of elements in x where its value is more than its corresponding element in y, and elements in x where its value is equals to its corresponding element in y.

In [6]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

greater_pos = np.where(x > y)
equal_pos = np.where(x == y)

print(f"Positions where x is greater than y: {greater_pos}")
print(f"Positions where x is equal to y: {equal_pos}")

Positions where x is greater than y: (array([1, 2, 4, 5, 6, 7, 8, 9]),)
Positions where x is equal to y: (array([0]),)


#### 4. Extract the first four columns of this 2-D array.

In [7]:
arr = np.arange(100).reshape(5,-1)
result = arr[:, :4]

result

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])

## Additional questions

#### 1. Generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive).

In [8]:
arr = np.random.randint(30, 41, size=10)
arr

array([40, 36, 30, 35, 34, 40, 30, 39, 38, 40])

#### 2. Consider the following matrices:
- A = ```((1, 2, 3), (4, 5, 6), (7, 8, 10))```
- B = ```((7, 8, 10) ,(4, 5, 6), (1, 2, 3))```

#### Write a python program to perform the following using Numeric Python (numpy).
- Add and Subtract of the Matrix A and B, print the resultant matrix C for add and E for subtract.
- Compute the sum of all elements of Matrix A, sum of each column of Matrix B and sum of each row of Matrix C
- Product of two matrices A and B, and print the resultant matrix D
- Sort the elements of resultant matrix C and print the resultant Matrix E.
- Transpose the Matrix E and print the result

In [9]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 10]])

B = np.array([[7, 8, 10],
              [4, 5, 6],
              [1, 2, 3]])

In [10]:
# Addition
C = A + B
C

array([[ 8, 10, 13],
       [ 8, 10, 12],
       [ 8, 10, 13]])

In [11]:
# Subtraction
E = A - B
E

array([[-6, -6, -7],
       [ 0,  0,  0],
       [ 6,  6,  7]])

In [12]:
# Sum of all elements of Matrix A, sum of each column of Matrix B and sum of each row of Matrix C
print(f"Sum of all elements of A: {np.sum(A)}")
print(f"Sum of each column of B: {np.sum(B, axis=0)}")
print(f"Sum of each row of C: {np.sum(C, axis=1)}")

Sum of all elements of A: 46
Sum of each column of B: [12 15 19]
Sum of each row of C: [31 30 31]


In [13]:
# Matrix multiplication
D = np.matmul(A, B)
D

array([[ 18,  24,  31],
       [ 54,  69,  88],
       [ 91, 116, 148]])

In [14]:
# Sort
E = np.sort(C)
E

array([[ 8, 10, 13],
       [ 8, 10, 12],
       [ 8, 10, 13]])

In [15]:
# Transpose
E.T

array([[ 8,  8,  8],
       [10, 10, 10],
       [13, 12, 13]])